export const BREATHING_TECHNIQUES = [
  { id: 'box', name: 'Box Breathing', nameHi: 'बॉक्स श्वास',
    sanskritName: 'Sama Vritti', pattern: [4,4,4,4],
    phases: ['inhale','hold','exhale','hold'],
    goal: ['focus','calm'], color: '#4DB896',
    effect: 'Focus & Calm', effectHi: 'ध्यान और शांति',
    science: 'Used by Navy SEALs — balances autonomic nervous system' },
  { id: 'four78', name: '4-7-8 Method', nameHi: '4-7-8 विधि',
    sanskritName: 'Pranayama', pattern: [4,7,8,0],
    phases: ['inhale','hold','exhale',''],
    goal: ['sleep'], color: '#9B59B6',
    effect: 'Deep Sleep', effectHi: 'गहरी नींद',
    science: 'Dr. Andrew Weil — shifts brainwaves to delta/theta' },
  { id: 'nadi', name: 'Nadi Shodhana', nameHi: 'नाड़ी शोधन',
    sanskritName: 'Anulom Vilom', pattern: [4,0,4,0],
    phases: ['inhale-left','','exhale-right',''],
    goal: ['balance','clarity'], color: '#2ECC71',
    effect: 'Balance & Clarity', effectHi: 'संतुलन और स्पष्टता',
    science: 'Activates both brain hemispheres — improves creativity' },
  { id: 'coherence', name: 'Coherence Breathing', nameHi: 'सुसंगत श्वास',
    sanskritName: 'Pranayama', pattern: [5,0,5,0],
    phases: ['inhale','','exhale',''],
    goal: ['stress'], color: '#2D8B6F',
    effect: 'Stress Reduction', effectHi: 'तनाव में कमी',
    science: 'Optimises HRV — used by elite athletes' },
  { id: 'extended', name: 'Extended Exhale', nameHi: 'विस्तारित श्वास',
    sanskritName: 'Dirga Rechaka', pattern: [4,0,8,0],
    phases: ['inhale','','exhale',''],
    goal: ['anxiety'], color: '#8E44AD',
    effect: 'Anxiety Relief', effectHi: 'चिंता से मुक्ति',
    science: 'Activates vagus nerve — reduces cortisol immediately' },
  { id: 'kapalbhati', name: 'Kapalbhati', nameHi: 'कपालभाति',
    sanskritName: 'Kapalbhati Pranayama', pattern: [1,0,1,0],
    phases: ['passive-inhale','','forceful-exhale',''],
    goal: ['energy','morning'], color: '#E8832A',
    effect: 'Morning Energy', effectHi: 'सुबह की ऊर्जा',
    science: '60 rounds — oxygenates blood, clears sinuses' },
  { id: 'bhramari', name: 'Bhramari', nameHi: 'भ्रामरी',
    sanskritName: 'Bhramari Pranayama', pattern: [4,0,8,0],
    phases: ['inhale','','hum-exhale',''],
    goal: ['anxiety','anger'], color: '#E74C3C',
    effect: 'Anxiety & Anger Relief', effectHi: 'चिंता और क्रोध से राहत',
    science: 'Humming creates vagal tone — reduces cortisol 20%' },
]
