export const MEDITATIONS = [
  // FREE TIER (3 sessions)
  {
    id: 'body-scan',
    title: 'Body Scan', titleHi: 'शरीर स्कैन',
    duration: 10,
    category: 'sleep',
    level: 'beginner',
    free: true,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/body_scan_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/body_scan_hi.mp3',
    thumbnail: 'moon',
    description: 'A progressive relaxation from head to toe',
    descriptionHi: 'सिर से पैर तक प्रगतिशील विश्राम',
    script_preview: 'Find a comfortable position... either lying on your back or sitting tall. Let your arms rest naturally...',
    tags: ['sleep', 'beginner', 'relaxation']
  },
  {
    id: 'morning-gratitude',
    title: 'Morning Gratitude', titleHi: 'सुबह की कृतज्ञता',
    duration: 5,
    category: 'morning',
    level: 'beginner',
    free: true,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/morning_gratitude_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/morning_gratitude_hi.mp3',
    thumbnail: 'sunrise',
    description: 'Set a positive intention for your day',
    descriptionHi: 'अपने दिन के लिए सकारात्मक इरादा बनाएं',
    script_preview: 'Take a deep breath in... and out. Think of one simple thing you are grateful for today.',
    tags: ['morning', 'beginner', 'gratitude']
  },
  {
    id: 'sos-3min',
    title: 'SOS — 3-Min Calm', titleHi: '3 मिनट की शांति',
    duration: 3,
    category: 'stress',
    level: 'beginner',
    free: true,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/sos_calm_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/sos_calm_hi.mp3',
    thumbnail: 'shield',
    description: 'Emergency calm for high-stress moments',
    descriptionHi: 'तनाव के क्षणों के लिए आपातकालीन शांति',
    script_preview: 'You are safe. Notice your feet on the ground. Breathe in for four counts... hold... and release.',
    tags: ['stress', 'beginner', 'quick']
  },
  // PREMIUM (7 sessions)
  {
    id: 'pre-exam-focus',
    title: 'Pre-Exam Focus', titleHi: 'परीक्षा से पहले का ध्यान',
    duration: 10,
    category: 'focus',
    level: 'beginner',
    free: false,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/pre_exam_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/pre_exam_hi.mp3',
    thumbnail: 'target',
    description: 'Center your mind before JEE, UPSC, or any exam',
    descriptionHi: 'JEE, UPSC या किसी भी परीक्षा से पहले मन को केंद्रित करें',
    script_preview: 'Visualize your success. Your mind is sharp and ready. Let go of the outcome, focus only on the action.',
    tags: ['focus', 'students', 'exam']
  },
  {
    id: 'ranthambore-sleep-story',
    title: 'Sleep Story: Ranthambore Forest', titleHi: 'नींद की कहानी: रणथंभोर',
    duration: 20,
    category: 'sleep',
    level: 'all',
    free: false,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/ranthambore_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/ranthambore_hi.mp3',
    thumbnail: 'moon-stars',
    description: 'An Indian folk-setting sleep story through a tiger reserve',
    descriptionHi: 'बाघ अभयारण्य में एक भारतीय लोक-कथा',
    script_preview: 'The sun is setting over the ancient ruins of Ranthambore. The jungle goes quiet as the stars begin to emerge...',
    tags: ['sleep', 'story', 'indian']
  },
  {
    id: 'yoga-nidra',
    title: 'Yoga Nidra', titleHi: 'योग निद्रा',
    duration: 15,
    category: 'sleep',
    level: 'intermediate',
    free: false,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/yoga_nidra_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/yoga_nidra_hi.mp3',
    thumbnail: 'body',
    description: 'Ancient yogic sleep technique — 1 hour of rest in 15 minutes',
    descriptionHi: 'प्राचीन योगिक तकनीक — 15 मिनट में 1 घंटे का विश्राम',
    script_preview: 'Bring your awareness to your right thumb... right index finger... right middle finger...',
    tags: ['sleep', 'advanced', 'yoga']
  },
  {
    id: 'stress-debrief',
    title: 'End-of-Day Debrief', titleHi: 'दिन के अंत का विश्राम',
    duration: 10,
    category: 'stress',
    level: 'beginner',
    free: false,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/debrief_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/debrief_hi.mp3',
    thumbnail: 'sunset',
    description: 'Release the weight of the day before sleep',
    descriptionHi: 'सोने से पहले दिन का भार छोड़ें',
    script_preview: 'Acknowledge the challenges you faced today. Now, imagine taking them off like a heavy coat, and leaving them at the door.',
    tags: ['stress', 'evening', 'release']
  },
  {
    id: 'single-point',
    title: 'Single-Point Attention', titleHi: 'एकाग्रता ध्यान',
    duration: 15,
    category: 'focus',
    level: 'intermediate',
    free: false,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/single_point_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/single_point_hi.mp3',
    thumbnail: 'eye',
    description: 'Train sustained attention — recommended before deep work',
    descriptionHi: 'एकाग्रता का प्रशिक्षण — गहरे काम से पहले',
    script_preview: 'Focus entirely on the sensation of air entering your nostrils. When your mind wanders, gently guide it back. Just this one point of focus.',
    tags: ['focus', 'intermediate', 'attention']
  },
  {
    id: 'self-compassion',
    title: 'Self-Compassion', titleHi: 'आत्म-करुणा',
    duration: 10,
    category: 'morning',
    level: 'beginner',
    free: false,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/self_compassion_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/self_compassion_hi.mp3',
    thumbnail: 'heart',
    description: 'Begin your day with kindness toward yourself',
    descriptionHi: 'अपने प्रति दया के साथ दिन शुरू करें',
    script_preview: 'Place a hand over your heart. Say to yourself: "May I be kind to myself today. May I forgive my own mistakes."',
    tags: ['morning', 'emotional', 'self-love']
  },
  {
    id: 'anxiety-relief',
    title: 'Tension Release', titleHi: 'तनाव मुक्ति',
    duration: 12,
    category: 'stress',
    level: 'beginner',
    free: false,
    language: ['en', 'hi'],
    audioUrlEn: 'CLOUDINARY_URL/tension_release_en.mp3',
    audioUrlHi: 'CLOUDINARY_URL/tension_release_hi.mp3',
    thumbnail: 'cloud',
    description: 'Progressive muscle relaxation for anxiety and anger',
    descriptionHi: 'चिंता और क्रोध के लिए प्रगतिशील मांसपेशी विश्राम',
    script_preview: 'Squeeze your hands into tight fists. Squeeze them as hard as you can... now let go. Feel the tension drain away from your fingers.',
    tags: ['stress', 'anxiety', 'body']
  },
];
