export const INDIA_THEMES = [
  {
    id: 'ganga',
    name: 'Ganga Ghat Dawn',
    nameHi: 'गंगा घाट भोर',
    emoji: '🌅',
    gradientColors: ['#FFD89B', '#FF8C42', '#8B5A2B', '#1A3A5C'],
    ambientSound: 'ganga_water.mp3',
    free: true,
    description: 'Golden ghats, floating diyas, morning mist',
    descriptionHi: 'सुनहरे घाट, तैरते दीए, सुबह की धुंध',
    particleType: 'fireflies',
  },
  {
    id: 'rajasthan',
    name: 'Rajasthan Dusk',
    nameHi: 'राजस्थान की संध्या',
    emoji: '🏜️',
    gradientColors: ['#FF7F50', '#E8832A', '#8B1A1A', '#1A0A00'],
    ambientSound: 'desert_wind.mp3',
    free: true,
    description: 'Sand dunes, orange sky, rising stars',
    descriptionHi: 'रेत के टीले, नारंगी आकाश, उगते तारे',
    particleType: 'dust',
  },
  {
    id: 'kerala',
    name: 'Kerala Backwaters',
    nameHi: 'केरल के जलमार्ग',
    emoji: '🌴',
    gradientColors: ['#1A4D2E', '#2D7A5F', '#4AA87D', '#B5D9C8'],
    ambientSound: 'water_ripples.mp3',
    free: false,
    description: 'Misty canals, swaying palms, mirror reflections',
    descriptionHi: 'धुंधली नहरें, झूमते ताड़, दर्पण प्रतिबिंब',
    particleType: 'rain',
  },
  {
    id: 'himalaya',
    name: 'Himalayan Dawn',
    nameHi: 'हिमालय की भोर',
    emoji: '🏔️',
    gradientColors: ['#C9D6DF', '#E2EBF0', '#F9FCFF', '#FFB347'],
    ambientSound: 'himalayan_wind.mp3',
    free: false,
    description: 'First light on snow peaks, monastery silence',
    descriptionHi: 'बर्फीली चोटियों पर पहली रोशनी, मठ की शांति',
    particleType: 'snow',
  },
  {
    id: 'mysore',
    name: 'Mysore Palace Night',
    nameHi: 'मैसूर महल की रात',
    emoji: '✨',
    gradientColors: ['#2C1654', '#4A235A', '#7B2D8B', '#FFD700'],
    ambientSound: 'night_crickets.mp3',
    free: false,
    description: 'Illuminated palace, twinkling stars, velvet sky',
    descriptionHi: 'रोशन महल, टिमटिमाते तारे, मखमली आकाश',
    particleType: 'stars',
  },
  {
    id: 'coorg',
    name: 'Coorg Forest Rain',
    nameHi: 'कूर्ग का वन-वर्षा',
    emoji: '☕',
    gradientColors: ['#1A2A1A', '#2D4A2D', '#4A7A4A', '#8FBC8F'],
    ambientSound: 'forest_rain.mp3',
    free: false,
    description: 'Coffee plantation in monsoon, petrichor',
    descriptionHi: 'मानसून में कॉफी बागान, मिट्टी की सोंधी खुशबू',
    particleType: 'rain',
  },
  {
    id: 'mumbai',
    name: 'Mumbai Monsoon',
    nameHi: 'मुंबई मानसून',
    emoji: '🌧️',
    gradientColors: ['#1C2833', '#2E4057', '#546E7A', '#90A4AE'],
    ambientSound: 'city_rain.mp3',
    free: false,
    description: 'City lights in rain, chai warmth, urban quiet',
    descriptionHi: 'बारिश में शहर की रोशनी, चाय की गर्माहट',
    particleType: 'rain',
  },
  {
    id: 'spiti',
    name: 'Spiti Night Sky',
    nameHi: 'स्पीति का रात्रि आकाश',
    emoji: '🌌',
    gradientColors: ['#000010', '#0A0A2E', '#1A1A5E', '#4B0082'],
    ambientSound: 'deep_silence.mp3',
    free: false,
    description: 'Milky Way, single monastery lamp, cosmic silence',
    descriptionHi: 'आकाशगंगा, एकांत मठ-दीप, ब्रह्मांडीय मौन',
    particleType: 'stars',
  },
];
